language: node_js
sudo: 'false'
before_script: []
env:
  global:
    - secure: >-
        T1AipBtChOPlYJ4uhqtUZTiPuI8eKb3Xv0SqIAk4afWq8iLQxzitosHxv/l8xb00CTA/xCEwTIMQQFKiqM7BPexnP6eyZal2IDBL2UfaWmdU8fBAOTOFykYCV6T9dl4pdnNi2S/hmTYC5lZf41Pefgldmn8qG1kh5f+Sc2rYAqCmEHDTdS/qUwSegSIddwY/7EAI2Rr0hOluI6LIndoji8/57V9iiAD8eRkO81Q+8Lye4QeaSP0zQNvWuG+yA0JClpIq6yVWU8NoKHpZlrOX/LJRI4jANDW5HWia7+6bz3Luz18BjGzYweCKC9CTmGBT57cV8Ocy/TZRIkhUShRi4FW2HlLEujrThUr+dSlLwBOIw8Ld/ag20fGc7m9/mrgGKYK7XpHgoJdSPgVISRVmJUI2gxQ1wRC4T0vRNLwobJ4p0LNBX7GsJC+6W8cm0boF90bfvOEwfrcJjLXn9u9b9xhHw3w2PNT0wqtw+L8mC1ST9fvP0Vg0Nc7jjZj+hGkULmtUHQ3GpHXg6i/igHiubvyTnrF76M1w0/e3JxsRVOt1ZA+Ig/+aSvysCTFxRtMYbUIfnptbjf7zGLKrWix7nbEVp7dfF289D2DBoZbjQ/nn0x+DMeALr+jaMQGz2Fyoue3t9h5h6kXJU7WtS83MECqIXyAoFziczN5jeX/+eXU=
    - secure: >-
        o53kquvXTeAPDCmZb6F0pf+UyJjiLRieTVRKmnj69/0zE9jOocybxSWtRb3iKdWzXok2KG9mw0isru5ODDQNOH9LSLI6Pk83R6c/kHlYjyytJbH96pYqwGkkojbmVJTpFTsfTfpcY2ipLo9pHj3pt4WMLZjuQPXl5wyWmNjsIy9MRYeGI62ZklOptezr48ln9j4hDNfA6lUrpXioxpsoC2F5LP5omrG60ru3B5rrfkYELu6Vcoyjjy6Rlx9YpVXexicI4wlju7v+4PeFXOLqmk3BdOTAmmWnNmxueg/5TwZZtVxK53N+HFJ2Qqa+7yqOiWhPIqhm78Z0lRQlQExz+s1e8duPf/KgDCgczQpZnaFteVBGuIMgw+JFvnBU0VM4RnNBp9dRQSjtgHsb+HO5DIqxTHwyH8n/DpWKtAy4mfKbMcLP/IiNZH6kEerqdQtdE7kmyoTY0w1soVjRLU2q8qAN0haa+DZCG1YYTlYhp4RdVx26Lc7NsYRV8wQgFmoTjbrliHd6UPYYN5CSWDxd1ddbLyySevyy8MdWKWvhN0cqNdM5Xl2NYv9mVHDQaTZwQvZzOu5XwgKPKcsCmQkcy42uH+4bpKI6t8bfhZMBZZmQBKPkXRs72JIJx96WxXNpGyJum2pcHMIgAAOQhqTc03cybbmSoOKZmJ2HgO/v0fc=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
